# Вычисление экваториальных координат кометы NEOWISE

Created: 23.07.2020

Last updated: 23.07.2020

In [ ]:
import numpy as np
import pandas as pd
import math

Загружаем таблицу с положениями кометы в пикселях.

In [ ]:
comet = pd.read_csv('comet.csv')
comet

Загружаем положения звезд по пути кометы.

In [ ]:
stars = pd.read_csv('stars.csv')
stars

Теперь надо определить экваториальные координаты кометы, интерполируя значения координат звезд.

In [ ]:
def hours2radians(RA):
    (hh, mm, ss) = RA.split(':')
    return 2*math.pi*(float(hh) + float(mm)/60. + float(ss)/3600.)/24.

In [ ]:
stars.values

array([[1523, 136, 44.75, '5:55:32', 'beta Auriga'],
       [1608, 274, 37.195, '5:56:49', 'theta Auriga'],
       [1438, 436, 34.146, '6:49:00', 'theta Gemini'],
       [1665, 592, 22.439, '6:19:49', 'mu Gemini'],
       [1277, 535, 31.951, '7:30:58', 'alfa Gemini'],
       [1548, 589, 25.366, '6:40:43', 'epsilon Gemini'],
       [1210, 179, 49.146, '7:23:46', 'Lynx'],
       [1040, 341, 43.293, '8:19:02', 'Lynx'],
       [903, 249, 48.17100000000001, '8:55:20', 'iota Ursa Major'],
       [888, 267, 47.195, '9:00:00', 'kappa Ursa Major'],
       [796, 168, 51.82899999999999, '9:28:32', 'theta Ursa Major'],
       [614, 322, 43.049, '10:13:56', 'lambda Ursa Major'],
       [587, 346, 41.585, '10:19:13', 'mu Ursa Major'],
       [483, 275, 43.537, '10:50:49', 'omega Ursa Major'],
       [439, 230, 44.63399999999999, '11:06:15', 'psi Ursa Major'],
       [353, 112, 48.049, '11:43:38', 'xi Ursa Major'],
       [312, 433, 33.415, '11:16:00', 'nu Ursa Major']], dtype=object)

In [94]:
data = stars.values
n = len(stars)

In [95]:
for i in range(n):
    data[i][0] = float(data[i][0])
    data[i][1] = float(data[i][1])
    data[i][3] = hours2radians(data[i][3])
    data[i][4] = 1.

In [96]:
mean = data.mean(axis=0)
data -= mean

In [97]:
std = np.ones(5)
for i in range(n):
    for j in range(4):
        std[j] += pow(data[i][j], 2)
std = np.sqrt(std/n)
data /= std
    

In [67]:
from keras.datasets import boston_housing
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
np.random.shuffle(data)
data

In [69]:
m = 14
x_train = data[:m, :2]
y_train = data[:m, 2:4]
x_test = data[m:, :2]
y_test = data[m:, 2:4]

In [82]:
model = Sequential()
model.add(Dense(20, activation='relu', input_shape=(x_train.shape[1],)))
model.add(Dense(2))
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

In [ ]:
model.fit(x_train, y_train, epochs=1000, batch_size=1, verbose=2)

In [84]:
mse, mae = model.evaluate(x_test, y_test, verbose=0)
print(mse, mae)

0.04131016135215759 0.11391717195510864


In [85]:
pred = model.predict(x_test)


In [80]:
pred

array([[-0.99399596, -0.5296063 ],
       [-0.4360113 ,  1.2148613 ],
       [ 0.9239692 , -0.59285355]], dtype=float32)

In [86]:
y_test

array([[-1.046391264856423, -0.5498075402726168],
       [-0.8687268303739344, 1.1986895217554112],
       [1.04031635189658, -0.6057511583140999]], dtype=object)

In [ ]:
comet

In [105]:
data2 = comet.values[:,1:3]

In [ ]:
data2

In [107]:
data2 -= mean[:2]
data2 /= std[:2]

In [102]:
mean[:2]

array([981.4117647058823, 322.5882352941176], dtype=object)

In [103]:
std[:2]

array([457.05059043, 145.52119669])

In [108]:
data2

array([[1.6684985234846572, 0.9374013395422823],
       [1.6225517498897775, 0.7724769124041835],
       [1.572229093095385, 0.6006806341353306],
       [1.5153426115017243, 0.44949990925874006],
       [1.451892305108795, 0.3051910355129036],
       [1.381878173916597, 0.16088216176706713],
       [1.3053002179251307, 0.03031699028273891],
       [1.2199704955346395, -0.07963262780932696],
       [1.1280769483448798, -0.18271039477063872],
       [1.0318075179556077, -0.27204445947044226],
       [0.9224104379677984, -0.3545066730394916],
       [0.810825416380233, -0.4163533332162787],
       [0.6883006867938867, -0.4713281422623116],
       [0.5570241908085156, -0.5125592490468364],
       [0.42137181162363224, -0.5331748024390986],
       [0.2769676660397241, -0.553790355831361],
       [0.1259996956565474, -0.553790355831361],
       [-0.02934415792614169, -0.5400466535698528],
       [-0.16937242031053748, -0.5194311001775904],
       [-0.35753539788956934, -0.48507184452381985],

In [109]:
data[:,:2]

array([[1.1849634299385405, -1.2822065756912975],
       [1.370938465917816, -0.3338911196472293],
       [0.9989883939592649, 0.7793487635349376],
       [1.4956511371039187, 1.85135753993258],
       [0.6467297963985192, 1.4596620254795951],
       [1.2396619699324452, 1.8307419865403176],
       [0.5001377092148549, -0.9867169770688704],
       [0.12818763725630358, 0.12652290611329656],
       [-0.17156036191029367, -0.5056873979160822],
       [-0.20437948590663643, -0.3819940775625081],
       [-0.40567011308420536, -1.0623073395071656],
       [-0.8038754842398309, -0.004042265371031673],
       [-0.8629499074332478, 0.16088216176706713],
       [-1.090495833807891, -0.32701926851647517],
       [-1.186765264197163, -0.6362525694004104],
       [-1.374928241776195, -1.4471310028293962],
       [-1.4646338473661984, 0.7587332101426753]], dtype=object)

In [110]:
pred = model.predict(data2)

In [111]:
pred

array([[-1.7426003 , -1.3208131 ],
       [-1.5606366 , -1.3087403 ],
       [-1.3680301 , -1.2944605 ],
       [-1.1828632 , -1.2731699 ],
       [-0.9947348 , -1.246513  ],
       [-0.801977  , -1.2146128 ],
       [-0.6400873 , -1.1746572 ],
       [-0.43802756, -1.1310805 ],
       [-0.24919008, -1.0800911 ],
       [-0.07833718, -1.0253963 ],
       [ 0.1027039 , -0.9598171 ],
       [ 0.2722671 , -0.88895166],
       [ 0.43232784, -0.79246897],
       [ 0.61463207, -0.64850765],
       [ 0.7874284 , -0.48828885],
       [ 0.9538853 , -0.32470903],
       [ 1.0246133 , -0.18844162],
       [ 1.0157884 , -0.0368694 ],
       [ 0.9415912 ,  0.11014019],
       [ 0.83557457,  0.3075886 ],
       [ 0.72506034,  0.4818233 ],
       [ 0.63317996,  0.6446958 ],
       [ 0.49949992,  0.79846406],
       [ 0.34746164,  0.95038   ],
       [ 0.19542335,  1.102296  ],
       [ 0.04479332,  1.252117  ],
       [-0.10161211,  1.3956536 ],
       [-0.24520145,  1.5350004 ],
       [-0.37865633,

In [113]:
grads = pred*std[2:4]+mean[2:4]
grads

array([[26.214060796101435, 1.5347442803575015],
       [27.713487687475084, 1.541523932105295],
       [29.300614660107353, 1.5495429117438295],
       [30.826436349624117, 1.5614989816384144],
       [32.376662176381984, 1.5764685201767472],
       [33.96503570647028, 1.5943825084502037],
       [35.29904766506709, 1.6168201472875308],
       [36.96407121745191, 1.6412912665985333],
       [38.520139975311565, 1.669925076283978],
       [39.92801119991443, 1.7006396956074017],
       [41.419835588836314, 1.737466638850668],
       [42.81707939541124, 1.77726213154497],
       [44.13602043507202, 1.8314433471596523],
       [45.63825355419391, 1.912286848339093],
       [47.062138965500466, 2.0022599746063907],
       [48.433786350269855, 2.094120527027393],
       [49.01660255017657, 2.1706434093815594],
       [48.94388375163029, 2.2557609261422327],
       [48.332479735833736, 2.338316228887663],
       [47.45887576775734, 2.4491961683224597],
       [46.54821053649737, 2.547040111