# Вычисление экваториальных координат кометы NEOWISE

Created: 23.07.2020

Last updated: 23.07.2020

In [6]:
import numpy as np
import pandas as pd
import math

Загружаем таблицу с положениями кометы в пикселях.

In [2]:
comet = pd.read_csv('comet.csv')
comet

Date     X    Y  Dec  RA
0    7/1/2020  1744  459  NaN NaN
1    7/2/2020  1723  435  NaN NaN
2    7/3/2020  1700  410  NaN NaN
3    7/4/2020  1674  388  NaN NaN
4    7/5/2020  1645  367  NaN NaN
5    7/6/2020  1613  346  NaN NaN
6    7/7/2020  1578  327  NaN NaN
7    7/8/2020  1539  311  NaN NaN
8    7/9/2020  1497  296  NaN NaN
9   7/10/2020  1453  283  NaN NaN
10  7/11/2020  1403  271  NaN NaN
11  7/12/2020  1352  262  NaN NaN
12  7/13/2020  1296  254  NaN NaN
13  7/14/2020  1236  248  NaN NaN
14  7/15/2020  1174  245  NaN NaN
15  7/16/2020  1108  242  NaN NaN
16  7/17/2020  1039  242  NaN NaN
17  7/18/2020   968  244  NaN NaN
18  7/19/2020   904  247  NaN NaN
19  7/20/2020   818  252  NaN NaN
20  7/21/2020   742  259  NaN NaN
21  7/22/2020   664  266  NaN NaN
22  7/23/2020   587  275  NaN NaN
23  7/24/2020   511  285  NaN NaN
24  7/25/2020   435  295  NaN NaN
25  7/26/2020   360  305  NaN NaN
26  7/27/2020   288  315  NaN NaN
27  7/28/2020   218  325  NaN NaN
28  7/29/2020   152  334  NaN NaN
29  7/30/2020    87  342  NaN NaN

Загружаем положения звезд по пути кометы.

In [3]:
stars = pd.read_csv('stars.csv')
stars

X    Y     Dec        RA            Comment
0   1523  136  44.750   5:55:32        beta Auriga
1   1608  274  37.195   5:56:49       theta Auriga
2   1438  436  34.146   6:49:00       theta Gemini
3   1665  592  22.439   6:19:49          mu Gemini
4   1277  535  31.951   7:30:58        alfa Gemini
5   1548  589  25.366   6:40:43     epsilon Gemini
6   1210  179  49.146   7:23:46               Lynx
7   1040  341  43.293   8:19:02               Lynx
8    903  249  48.171   8:55:20    iota Ursa Major
9    888  267  47.195   9:00:00   kappa Ursa Major
10   796  168  51.829   9:28:32   theta Ursa Major
11   614  322  43.049  10:13:56  lambda Ursa Major
12   587  346  41.585  10:19:13      mu Ursa Major
13   483  275  43.537  10:50:49   omega Ursa Major
14   439  230  44.634  11:06:15     psi Ursa Major
15   353  112  48.049  11:43:38      xi Ursa Major
16   312  433  33.415  11:16:00      nu Ursa Major

Теперь надо определить экваториальные координаты кометы, интерполируя значения координат звезд.

In [110]:
RA = stars.RA.values
Dec = stars.Dec.values
n = len(stars)

In [111]:
def hours2radians(RA):
    (hh, mm, ss) = RA.split(':')
    return 2*math.pi*(float(hh) + float(mm)/60. + float(ss)/3600.)/24.

In [112]:
grad2radians = lambda x: math.pi*x/180.

In [113]:
ra = np.zeros(n)
for i in range(n):
    ra[i] = hours2radians(RA[i])
RA_mean = ra.mean()
ra -= RA_mean
RA_sd = math.sqrt((ra*ra).sum()/n)
ra /= RA_sd

In [114]:
dec = grad2radians(stars.Dec.values)
Dec_mean = dec.mean()
dec -= Dec_mean
Dec_sd = math.sqrt((dec*dec).sum()/n)
dec /= Dec_sd

In [115]:
X = stars.X.values
X_mean = X.mean()
x = X - X_mean
X_sd = math.sqrt((x*x).sum()/n)
x /= X_sd


In [116]:
Y = stars.Y.values
Y_mean = Y.mean()
y = Y - Y_mean
Y_sd = math.sqrt((y*y).sum()/n)
y /= Y_sd

In [117]:
x, y, dec, ra

(array([ 1.1849636 ,  1.37093866,  0.99898853,  1.49565135,  0.64672989,
         1.23966214,  0.50013778,  0.12818766, -0.17156039, -0.20437951,
        -0.40567017, -0.8038756 , -0.86295003, -1.09049599, -1.18676543,
        -1.37492844, -1.46463405]),
 array([-1.28220836, -0.33389158,  0.77934985,  1.85136011,  1.45966405,
         1.83074453, -0.98671835,  0.12652308, -0.5056881 , -0.38199461,
        -1.06230881, -0.00404227,  0.16088239, -0.32701972, -0.63625345,
        -1.44713301,  0.75873426]),
 array([ 0.50705731, -0.41018079, -0.78035405, -2.20167853, -1.04684481,
        -1.84631706,  1.04076726,  0.33016572,  0.92239437,  0.80390008,
         1.36650516,  0.30054215,  0.12280071,  0.3597893 ,  0.49297397,
         0.90758259, -0.86910337]),
 array([-1.43173737, -1.42068164, -0.97113006, -1.2225401 , -0.60959353,
        -1.04248974, -0.67162045, -0.19550642,  0.11721263,  0.15741527,
         0.40322565,  0.79433983,  0.83985495,  1.11208421,  1.24504006,
         1.56709