# Вычисление экваториальных координат кометы

Для нахождения регресcии между пиксельными координатами и экваториальными используется
модель Network из git@github.com:stacymiller/stepic_neural_networks_public.git

Данные для модели подготавливаются в модуле PrepareData

In [1]:
import math
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
import NotebookLoader
from PrepareData import load_stars, load_comet
import Networks.stepik

importing Jupyter notebook from PrepareData.ipynb
PrepareData v1.04 26.07.2020


In [2]:
(x_train, y_train), (x_test, y_test), (mean, std) = load_stars()

In [3]:
train_data = list(zip(x_train, y_train))

In [5]:
train_data

[(array([-0.03501677071309596, 0.20538485182676028], dtype=object),
  array([0.48398026439693964, -0.030799535163201882], dtype=object)),
 (array([-1.015086729901319, -1.6090997030986252], dtype=object),
  array([1.1769032424653145, 1.192949453011883], dtype=object)),
 (array([-1.015086729901319, -0.0936313295092583], dtype=object),
  array([0.06266399285583082, 0.9937660909607826], dtype=object)),
 (array([-0.8928027716906785, 0.7082757022555188], dtype=object),
  array([-0.39837048440338924, 0.802609336803867], dtype=object)),
 (array([-0.8604334886349206, -0.8071926713338481], dtype=object),
  array([0.7960472714688958, 0.9238728591437179], dtype=object)),
 (array([1.409012912274323, 1.5305702009295699], dtype=object),
  array([-1.7464663993620815, -1.2596114606253892], dtype=object)),
 (array([-0.7813085744986237, -0.5013806676947382], dtype=object),
  array([0.6442727469376214, 0.8077957603662637], dtype=object)),
 (array([-0.218442708029057, -1.2285336541255107], dtype=object),
 

In [4]:
model = Networks.stepik.Network([2, 3, 2])
epochs = 10
mini_batch_size = 2
eta = 0.001
model.SGD(train_data, epochs, mini_batch_size, eta, test_data=None)

input [-0.03501677071309596 0.20538485182676028] [0.48398026439693964 -0.030799535163201882]
z= [[-2.8814841950223724 -2.175496725124113 -2.3751079381691977]
 [-1.421186064278872 -0.7151985943806124 -0.9148098074256971]
 [-2.111058874755546 -1.4050714048572868 -1.6046826179023714]] [[ 0.43627834 -2.01225105]
 [-1.02703013  1.17565266]
 [ 0.10250775  0.39634278]] [-0.03501677071309596 0.20538485182676028]


TypeError: loop of ufunc does not support argument 0 of type float which has no callable exp method